### ISSUE TITLE
Xcode 14 build issue

### ISSUE THREAD

**Issue by SunnyGit** [apptentive/apptentive-kit-ios#34] opened 2022-11-15 02:20 UTC
Having challenge building the app with Xcode 14 and above.

While building the app, we are running into the issue to select development team else we cannot proceed to build.

Signing for "ApptentiveKit-ApptentiveKit" requires a development team. Select a development team in the Signing & Capabilities editor.

Please suggest how to overcome Build automation with the above mentioned issue

**Comment by SunnyGit** [comment] 2022-11-15 02:21
<img width="532" alt="Screen Shot 2022-11-14 at 8 20 42 PM" src="https://user-images.githubusercontent.com/6401619/201810740-31cdac82-5e2a-4637-9734-62176864369c.png">

**Comment by frankus** [comment] 2022-11-15 19:31
I haven't been able to reproduce this with either the SwiftPM or sub-project integration methods.

**Comment by SunnyGit** [comment] 2022-11-15 21:04
@frankus  We are using cocoapods in this case. I see that in podspec we have resource_bundles which is creating two section on pods target.
<img width="307" alt="Screen Shot 2022-11-15 at 3 04 51 PM" src="https://user-images.githubusercontent.com/6401619/202025034-38f986e1-a210-436c-823d-9a77a89f2c82.png">




pod 'ApptentiveKit'

**Comment by frankus** [comment] 2022-11-16 20:21
I've done some more investigation, and this seems to be a more widespread issue with Xcode 14 and/or CocoaPods when building resource bundles (for example, adding the Firebase pod results in the same issue). 

The most straightforward resolution is to go to the build settings for the Pods project and set your development team in the Signing section of the build settings. 

Depending on how committed you are to CocoaPods, you could also consider integrating using Swift Package Manager. Since it's a first-party Apple solution it may be less likely to break with updates to the development tools.

**Closed by frankus** 2022-11-16 20:21 UTC
