### ISSUE TITLE
Message Center Top Spacing / Padding

### ISSUE THREAD

**Issue by derekquinn** [apptentive/apptentive-kit-ios#6] opened 2022-03-25 18:57 UTC
I have noticed a UI glitch with the message center that consistently appears in my smoke testing. 

As you can see below, the message center chat view & data entry views appear with a UI Glitch. 

I am seeing the same behavior when I toggle the theme.

`Apptentive.shared.theme = .none` and `Apptentive.shared.theme = .apptentive` produce the same UI glitch. 
<img width="300" alt="Screen Shot 2022-03-25 at 2 45 25 PM" src="https://user-images.githubusercontent.com/45957246/160184387-8bd2c155-fa08-4802-b0d8-d75c09a72a46.png">

<img width="300" alt="Screen Shot 2022-03-25 at 2 45 37 PM" src="https://user-images.githubusercontent.com/45957246/160184097-105ca0d9-a68c-4557-a5c3-23df2777f3e2.png">

**Comment by derekquinn** [comment] 2022-04-05 18:56
In addition to the screenshots above, I was able to collect a video of the glitch and recreate it. 

https://drive.google.com/file/d/1DOL4cY7bS75pv7ZXZjDWHowBwtcgYYWs/view

Thanks again!

**Comment by CaseyApptentive** [comment] 2022-04-05 23:24
Hi @derekquinn. Thanks for reaching out. Were you also able to get in touch with anyone from my team directly? We got a similar report via email an I want to be sure we're not crossing wires on our responses. 

Let me know. Thanks again.

**Comment by frankus** [comment] 2022-04-06 19:20
I've tracked down the cause* and we'll include a fix in our next release. 

*The view controller tries to auto-scroll to the last message when presented. But the OS also will attempt to scroll the active (first responder) text field into view, and the two scrolling operations interfere. The fix keeps the OS in charge of scrolling if the profile view is active and otherwise actively scrolls down to the last message.

**Comment by frankus** [comment] 2022-04-14 00:29
This should be addressed by the v6.0.1 release. Please check it out and let me know :).

**Comment by derekquinn** [comment] 2022-04-15 02:15
@frankus Thanks so much!

**Closed** 2022-04-18 15:58 UTC
